version: "2"
services:
  app:
    container_name: "parking.ms"
    restart: always
    build: .
    environment:
      - API_HOST=localhost
      - API_PORT=3000
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql
    command: npm start

  mysql:
    container_name: "mysql"
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - SQL_HOST=localhost
      - SQL_DB=parking
      - SQL_USER=root
      - SQL_PWD=null
      - SQL_DIALECT=mysql
      - MYSQL_ALLOW_EMPTY_PASSWORD=true